// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCco-1MDD4GPq4kUVuTUKtCJcjpJX7lhxk',
    appId: '1:1068447590071:web:910150da01de7cef438f32',
    messagingSenderId: '1068447590071',
    projectId: 'rickandmorty-2253a',
    authDomain: 'rickandmorty-2253a.firebaseapp.com',
    storageBucket: 'rickandmorty-2253a.appspot.com',
    measurementId: 'G-EHZGTZV2D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDztWl67u7-y3ZdzsAzgqg-fnuwpWbgIvI',
    appId: '1:1068447590071:android:e179fb1f24176e9b438f32',
    messagingSenderId: '1068447590071',
    projectId: 'rickandmorty-2253a',
    storageBucket: 'rickandmorty-2253a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqyf6IZX6pg7yDs0ebicHf62sIKehtbw',
    appId: '1:1068447590071:ios:bd17785a6ee23df3438f32',
    messagingSenderId: '1068447590071',
    projectId: 'rickandmorty-2253a',
    storageBucket: 'rickandmorty-2253a.appspot.com',
    iosClientId: '1068447590071-3alnei65b3mv7o1j44gtj0g8n5kc7t92.apps.googleusercontent.com',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqyf6IZX6pg7yDs0ebicHf62sIKehtbw',
    appId: '1:1068447590071:ios:2f8f55fe6ae06ca1438f32',
    messagingSenderId: '1068447590071',
    projectId: 'rickandmorty-2253a',
    storageBucket: 'rickandmorty-2253a.appspot.com',
    iosClientId: '1068447590071-ibn04ea50khsi7r5g8td3kuuak3vr21v.apps.googleusercontent.com',
    iosBundleId: 'com.example.rickAndMorty.RunnerTests',
  );
}
